
package EduSys.UI;


import EduSys.dao.impl.NhanVienImpl;
import EduSys.utils.Auth;
import EduSys.utils.XMsgBox;

/**
 *
 * @author acer
 */
    public class ChangePasswordJDialog extends javax.swing.JDialog{

    /**
     * Creates new form ChangePassword
     */
    public ChangePasswordJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuDe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblCPass = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lblNpass = new javax.swing.JLabel();
        lblConfirmPass = new javax.swing.JLabel();
        txtNPass = new javax.swing.JPasswordField();
        txtCPass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTieuDe.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        lblTieuDe.setForeground(new java.awt.Color(51, 102, 255));
        lblTieuDe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTieuDe.setText("Đổi mật khẩu");

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 10, 6));

        lblUsername.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblUsername.setText("Tên đăng nhập");
        jPanel1.add(lblUsername);

        lblCPass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblCPass.setText("Mật khẩu");
        jPanel1.add(lblCPass);

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername);

        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(txtPass);

        lblNpass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblNpass.setText("Mật khẩu mới");
        jPanel1.add(lblNpass);

        lblConfirmPass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblConfirmPass.setText("Xác nhận mật khẩu");
        jPanel1.add(lblConfirmPass);

        txtNPass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNPassActionPerformed(evt);
            }
        });
        jPanel1.add(txtNPass);

        txtCPass.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(txtCPass);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/icon/No.png"))); // NOI18N
        btnCancel.setText("Hủy bỏ");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);

        btnConfirm.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/icon/Tick.png"))); // NOI18N
        btnConfirm.setText("Xác nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel2.add(btnConfirm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTieuDe)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        changePassword();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        cancel();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtNPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNPassActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangePasswordJDialog dialog = new ChangePasswordJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCPass;
    private javax.swing.JLabel lblConfirmPass;
    private javax.swing.JLabel lblNpass;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtCPass;
    private javax.swing.JPasswordField txtNPass;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    
    public void init(){
        this.setLocationRelativeTo(null);
        this.setTitle("Đổi mật khẩu");
        txtUsername.setText(Auth.user.getMaNV());
    }
    
    
    private void cancel(){
        this.dispose();
    }
    
    
    NhanVienImpl dao = new NhanVienImpl();
    public void changePassword() {
        String Pass = new String (txtPass.getPassword());
        String newPass = new String (txtNPass.getPassword());
        String CPass = new String(txtCPass.getPassword());
        if(!Pass.equals(Auth.user.getMatKhau())){
            XMsgBox.alert(null,"Sai mật khẩu !");
        }
        else if(!newPass.equals(CPass)){
            XMsgBox.alert(null,"Xác nhận mật khẩu chưa trùng khớp !!");
        } else {
            Auth.user.setMatKhau(newPass);
            dao.update(Auth.user);
            XMsgBox.alert(null,"Đổi mật khẩu thành công");
            this.dispose();
        }
    }
}
