
package EduSys.UI;

import EduSys.controller.KhoaHocController;
import EduSys.entity.KhoaHoc;
import EduSys.dao.impl.ChuyenDeImpl;
import EduSys.dao.impl.HocVienImpl;
import EduSys.dao.impl.KhoaHocImpl;
import EduSys.dao.impl.NguoiHocImpl;
import EduSys.entity.ChuyenDe;
import EduSys.entity.HocVien;
import EduSys.entity.NguoiHoc;
import EduSys.utils.Auth;
import EduSys.utils.XDate;
import EduSys.utils.XMsgBox;
import edusys.utils.XCheck;
import java.text.ParseException;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;


public class CourseJDialog extends javax.swing.JDialog implements KhoaHocController {
    int row = -1;
    ChuyenDeImpl CDdao = new ChuyenDeImpl();
    HocVienImpl HVDAO = new HocVienImpl();
    NguoiHocImpl NHDAO = new NguoiHocImpl();
    KhoaHocImpl KHDAO = new KhoaHocImpl();
    public CourseJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        pnlTieuDe = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        pnlCapNhat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        pnlDanhSach = new javax.swing.JPanel();
        pnlbtn1 = new javax.swing.JPanel();
        btnMoveFirst = new javax.swing.JButton();
        btnMovePre = new javax.swing.JButton();
        btnMoveNext = new javax.swing.JButton();
        btnMoveLast = new javax.swing.JButton();
        pnlbtn2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        pnlThongTin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboChuyenDe = new javax.swing.JComboBox<>();
        txtMaKH = new javax.swing.JTextField();
        txtKhaiGiang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtThoiLuong = new javax.swing.JTextField();
        txtHocPhi = new javax.swing.JTextField();
        txtNguoiTao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgayTao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnSelectAll2 = new javax.swing.JButton();
        btnClearSelect2 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblNguoiHoc = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnSelectAll1 = new javax.swing.JButton();
        btnClearSelect1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHocVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlTieuDe.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblList.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "KHÓA HỌC", "NGÀY KHAI GIẢNG", "THỜI LƯỢNG", "HỌC PHÍ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblList.setRowHeight(25);
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        javax.swing.GroupLayout pnlCapNhatLayout = new javax.swing.GroupLayout(pnlCapNhat);
        pnlCapNhat.setLayout(pnlCapNhatLayout);
        pnlCapNhatLayout.setHorizontalGroup(
            pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1122, Short.MAX_VALUE))
        );
        pnlCapNhatLayout.setVerticalGroup(
            pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Danh Sách", pnlCapNhat);

        pnlbtn1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnMoveFirst.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnMoveFirst.setText("|<");
        btnMoveFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveFirstActionPerformed(evt);
            }
        });
        pnlbtn1.add(btnMoveFirst);

        btnMovePre.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnMovePre.setText("<<");
        btnMovePre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovePreActionPerformed(evt);
            }
        });
        pnlbtn1.add(btnMovePre);

        btnMoveNext.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnMoveNext.setText(">>");
        btnMoveNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveNextActionPerformed(evt);
            }
        });
        pnlbtn1.add(btnMoveNext);

        btnMoveLast.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        btnMoveLast.setText(">|");
        btnMoveLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveLastActionPerformed(evt);
            }
        });
        pnlbtn1.add(btnMoveLast);

        pnlbtn2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlbtn2.add(btnThem);

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlbtn2.add(btnSua);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlbtn2.add(btnXoa);

        btnMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EduSys/icon/Refresh.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        pnlbtn2.add(btnMoi);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Chuyên đề");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel8.setText("Mã KH");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Khai giảng");

        cboChuyenDe.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cboChuyenDe.setForeground(new java.awt.Color(255, 0, 51));
        cboChuyenDe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboChuyenDeItemStateChanged(evt);
            }
        });
        cboChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChuyenDeActionPerformed(evt);
            }
        });

        txtMaKH.setEditable(false);
        txtMaKH.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtMaKH.setForeground(new java.awt.Color(255, 0, 0));

        txtKhaiGiang.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel7.setText("Thời lượng");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel5.setText("Học Phí");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Người Tạo");

        txtThoiLuong.setEditable(false);
        txtThoiLuong.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtThoiLuong.setForeground(new java.awt.Color(255, 0, 0));

        txtHocPhi.setEditable(false);
        txtHocPhi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtHocPhi.setForeground(new java.awt.Color(255, 0, 0));

        txtNguoiTao.setEditable(false);
        txtNguoiTao.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNguoiTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNguoiTaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Ngày Tạo");

        txtNgayTao.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNgayTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlThongTinLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKhaiGiang, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(284, 284, 284))
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboChuyenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtKhaiGiang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("Ghi chú");

        txtGhiChu.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(txtGhiChu);

        javax.swing.GroupLayout pnlDanhSachLayout = new javax.swing.GroupLayout(pnlDanhSach);
        pnlDanhSach.setLayout(pnlDanhSachLayout);
        pnlDanhSachLayout.setHorizontalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachLayout.createSequentialGroup()
                .addComponent(pnlbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                .addGroup(pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDanhSachLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(pnlDanhSachLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDanhSachLayout.setVerticalGroup(
            pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDanhSachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(pnlDanhSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlbtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlbtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tabs.addTab("Cập Nhật", pnlDanhSach);

        jSplitPane1.setDividerLocation(600);
        jSplitPane1.setDividerSize(15);
        jSplitPane1.setOneTouchExpandable(true);

        btnSelectAll2.setText("Chọn tất cả");
        btnSelectAll2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAll2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnSelectAll2);

        btnClearSelect2.setText("Bỏ chọn");
        btnClearSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSelect2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnClearSelect2);

        btnAdd.setText("Thêm học viên");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel6.add(btnAdd);

        tblNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ NH", "HỌ TÊN", "GIỚI TÍNH", "NGÀY SINH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNguoiHoc.setRowHeight(25);
        tblNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiHocMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblNguoiHoc);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel4);

        btnSelectAll1.setText("Chọn tất cả");
        btnSelectAll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAll1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSelectAll1);

        btnClearSelect1.setText("Bỏ chọn");
        btnClearSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSelect1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnClearSelect1);

        btnDelete.setText("Xóa học viên");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);

        btnUpdate1.setText("Cập nhật điểm");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate1);

        tblHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ HV", "MÃ NH", "HỌ TÊN", "GIỚI TÍNH", "NGÀY SINH", "ĐIỂM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHocVien.setRowHeight(25);
        tblHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHocVienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblHocVien);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        tabs.addTab("Học Viên", jPanel1);

        javax.swing.GroupLayout pnlTieuDeLayout = new javax.swing.GroupLayout(pnlTieuDe);
        pnlTieuDe.setLayout(pnlTieuDeLayout);
        pnlTieuDeLayout.setHorizontalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTieuDeLayout.createSequentialGroup()
                .addComponent(tabs)
                .addContainerGap())
        );
        pnlTieuDeLayout.setVerticalGroup(
            pnlTieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTieuDeLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlTieuDe, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoveFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveFirstActionPerformed
        this.moveFirst();
    }//GEN-LAST:event_btnMoveFirstActionPerformed

    private void btnMovePreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovePreActionPerformed
        this.movePrevious();
    }//GEN-LAST:event_btnMovePreActionPerformed

    private void btnMoveNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveNextActionPerformed
        this.moveNext();
    }//GEN-LAST:event_btnMoveNextActionPerformed

    private void btnMoveLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveLastActionPerformed
        this.moveLast();
    }//GEN-LAST:event_btnMoveLastActionPerformed

    private void txtNgayTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTaoActionPerformed

    private void txtNguoiTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNguoiTaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNguoiTaoActionPerformed

    private void cboChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChuyenDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChuyenDeActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void cboChuyenDeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboChuyenDeItemStateChanged
        this.chonChuyenDe();
    }//GEN-LAST:event_cboChuyenDeItemStateChanged

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
         
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        if(evt.getClickCount() == 2){
            this.row = tblList.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblListMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        this.insertHocVien();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSelectAll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAll1ActionPerformed
        this.selectAllHV();
    }//GEN-LAST:event_btnSelectAll1ActionPerformed

    private void btnClearSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSelect1ActionPerformed
        this.clearSelectAllHV();
    }//GEN-LAST:event_btnClearSelect1ActionPerformed

    private void btnSelectAll2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAll2ActionPerformed
        this.selectAllNH();
    }//GEN-LAST:event_btnSelectAll2ActionPerformed

    private void btnClearSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSelect2ActionPerformed
        this.clearSelectAllNH();
    }//GEN-LAST:event_btnClearSelect2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       this.removeHocVien();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        this.updateDiem();
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void tblNguoiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiHocMouseClicked
        if(evt.getClickCount() == 2){
            this.insertHocVien();
        }
    }//GEN-LAST:event_tblNguoiHocMouseClicked

    private void tblHocVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHocVienMouseClicked
         if(evt.getClickCount() == 2){
            this.removeHocVien();
        }
    }//GEN-LAST:event_tblHocVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CourseJDialog dialog = new CourseJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearSelect1;
    private javax.swing.JButton btnClearSelect2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnMoveFirst;
    private javax.swing.JButton btnMoveLast;
    private javax.swing.JButton btnMoveNext;
    private javax.swing.JButton btnMovePre;
    private javax.swing.JButton btnSelectAll1;
    private javax.swing.JButton btnSelectAll2;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboChuyenDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlCapNhat;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JPanel pnlTieuDe;
    private javax.swing.JPanel pnlbtn1;
    private javax.swing.JPanel pnlbtn2;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblHocVien;
    private javax.swing.JTable tblList;
    private javax.swing.JTable tblNguoiHoc;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtKhaiGiang;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtNguoiTao;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables


    @Override
    public KhoaHoc getForm() {
        ChuyenDe chuyende = (ChuyenDe)cboChuyenDe.getSelectedItem();
        KhoaHoc kh = new KhoaHoc();
        kh.setMaKH(Integer.valueOf(txtMaKH.getText()));
        kh.setMaCD(chuyende.getMaCD());
        kh.setHocPhi(Double.valueOf(txtHocPhi.getText()));
        kh.setThoiLuong(Integer.valueOf(txtThoiLuong.getText()));
        kh.setGhiChu(txtGhiChu.getText());
        kh.setMaNV(txtNguoiTao.getText());
        try {
            kh.setNgayTao(XDate.toDate(txtNgayTao.getText(), "MM/dd/yyyy"));
            kh.setNgayKG(XDate.toDate(txtKhaiGiang.getText(), "MM/dd/yyyy"));
        } catch (ParseException ex) {
            XMsgBox.alert(null,"Lỗi Chuyển định dạng ngày tạo !!");
        }
        return kh; 
    }

    @Override
    public void setForm(KhoaHoc Entity) {
        Integer makh = Integer.valueOf(tblList.getValueAt(this.row, 0)+"");
        ChuyenDe cd = CDdao.SelectChuyenDeByMaKH(makh);
        cboChuyenDe.setSelectedItem(cd);
        txtMaKH.setText(Entity.getMaKH()+"");
        txtThoiLuong.setText(Entity.getThoiLuong()+"");
        txtKhaiGiang.setText(XDate.toString(Entity.getNgayKG(), "MM/dd/yyyy"));
        txtHocPhi.setText(Entity.getHocPhi()+"");
        txtNgayTao.setText(XDate.toString(Entity.getNgayTao(), "MM/dd/yyyy"));
        txtNguoiTao.setText(Entity.getMaNV());
    }
    
    
    
    
    KhoaHocImpl ddao = new KhoaHocImpl();
    @Override
    public void fillToTableKhoaHoc() {
        DefaultTableModel model = (DefaultTableModel)tblList.getModel();
        model.setRowCount(0);
        
        try {
            List<KhoaHoc> list = ddao.selectAll();
            for(KhoaHoc kh:list){
                String TenCD = CDdao.selectByID(kh.getMaCD()).getTenCD();
                Object [] values = {
                    kh.getMaKH(),
                    kh.getMaCD() +" - "+ TenCD,
                    kh.getNgayKG(),
                    kh.getThoiLuong(),
                    kh.getHocPhi()
                };
                model.addRow(values);
            }
        } catch (Exception e) {
            XMsgBox.alert(null,"Lỗi truy vẫn dữ liệu !!");
        }
    }
    
    
    
    
    @Override
    public void fillToTableHocVien() {
        Integer makh = Integer.valueOf(tblList.getValueAt(this.row, 0)+"");
        DefaultTableModel model = (DefaultTableModel)tblHocVien.getModel();
        model.setRowCount(0);
        try {
            List<HocVien> list = HVDAO.SelectByKhoaHoc(makh);
            for(HocVien hv:list){
                NguoiHoc nh = NHDAO.selectByID(hv.getMaNH());
                Object [] values = {
                    hv.getMaHV(),
                    hv.getMaNH(),
                    nh.getHoTen(),
                    nh.getGioiTinh()?"Nam":"Nữ",
                    XDate.toString(nh.getNgaySinh(), "MM/dd/yyyy"),
                    hv.getDiem()                    
                };
                model.addRow(values);
            }
        } catch (Exception e) {
        }
        
    }

    @Override
    public void fillToTableNguoiHoc() {
        DefaultTableModel model = (DefaultTableModel) tblNguoiHoc.getModel();
        int makh = Integer.valueOf(txtMaKH.getText());
        model.setRowCount(0);
        String keyword ="";
        try {
            List <NguoiHoc> list = NHDAO.SelectNotInCourseID(makh, keyword);
            for(NguoiHoc nh : list){
                Object [] values = {
                    nh.getMaNH(),
                    nh.getHoTen(),
                    nh.getGioiTinh()? "Nam":"Nữ",
                    XDate.toString(nh.getNgaySinh(), "MM/dd/yyy")
                };
                model.addRow(values);
            }
        } catch (Exception e) {
            XMsgBox.alert(null,"Lỗi Truy vấn dừ liệu");
        }
    }

    @Override
    public void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblList.getRowCount() - 1);
        // Trạng thái form
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);
        
        // Trạng thái điều hướng
        btnMoveFirst.setEnabled(edit && !first);
        btnMovePre.setEnabled(edit && !first);
        btnMoveNext.setEnabled(edit && !last);
        btnMoveLast.setEnabled(edit && !last);
    }

    @Override
    public void initialize() {
        this.setLocationRelativeTo(null);
        this.setTitle("EduSys - Quản lý khóa học");
        this.fillToTableKhoaHoc();
        this.fillComboboxChuyenDe();
        txtNguoiTao.setText(Auth.user.getMaNV());
        txtNgayTao.setText(XDate.toString(new Date(), "MM/dd/yyyy"));
        txtKhaiGiang.setText(XDate.toString(XDate.addDate(new Date(), 7), "MM/dd/yyyy"));
        this.row = -1;
        this.updateStatus();
    }

    @Override
    public void insert() {
        if(XCheck.checkDate(txtKhaiGiang.getText(), txtNgayTao.getText(), "MM/dd/yyyy") == false){
            try {
                KHDAO.insert(this.getForm());
                this.fillToTableKhoaHoc();
                this.clearForm();
                this.updateStatus();
                XMsgBox.alert(null,"Thêm khóa học thành công.");
            } catch (Exception e) {
                XMsgBox.alert(null,"Thêm khóa học thất bại.");
            }
        }else {
            XMsgBox.alert(null,"Ngày khai giảng không được bắt đầu trước ngày tạo !!");
        }
    }

    @Override
    public void update() {
        if(XCheck.checkDate(txtKhaiGiang.getText(), txtNgayTao.getText(), "MM/dd/yyyy") == false){
            try {
                KHDAO.update(this.getForm());
                this.fillToTableKhoaHoc();
                this.clearForm();
                this.updateStatus();
                XMsgBox.alert(null,"Cập nhật thành công.");
            } catch (Exception e) {
                XMsgBox.alert(null,"cập nhật thất bại.");
            }
        }else{
            XMsgBox.alert(null,"Ngày khai giảng không được bắt đầu trước ngày tạo !!");
        }
    }

    @Override
    public void delete() {
        Integer makh = Integer.valueOf(txtMaKH.getText());
        System.out.println("MAKH = " + makh);
        if(!Auth.isManager()){
            XMsgBox.alert(null,"Bạn không có quyền xóa.");
        }else{
            try {
                if(XMsgBox.confirm(null,"Bạn muốn xóa khóa học đang chọn ?")){
                    KHDAO.delete(makh);
                    this.clearForm();
                    this.fillToTableKhoaHoc();
                    tabs.setSelectedIndex(0);
                    this.updateStatus();
                    XMsgBox.alert(null,"Xóa khóa học thành công ");
                }
           } catch (Exception e) {
               XMsgBox.alert(null,"Xóa khóa học thất bại");
           }   
        }
    }

    @Override
    public void edit() {
        Integer makh = Integer.valueOf(tblList.getValueAt(this.row, 0)+"");
        KhoaHoc Entity = ddao.selectByID(makh);
        this.setForm(Entity);
        this.fillToTableHocVien();
        this.fillToTableNguoiHoc();
        tabs.setSelectedIndex(1);
        this.updateStatus();
    }

    @Override
    public void clearForm() {
        try {
            KhoaHoc kh = new KhoaHoc();
            this.setForm(kh);
            if(cboChuyenDe.getSelectedIndex() == 0){
                this.chonChuyenDe();
            }
            cboChuyenDe.setSelectedIndex(0);
            this.row = -1;
            this.updateStatus();
        } catch (Exception e) {
        }
   }

    @Override
    public void moveFirst() {
        this.row = 0;
        this.edit();
    }

    @Override
    public void movePrevious() {
        if(this.row > 0){
            --row;
            this.edit();
        }
    }

    @Override
    public void moveLast() {
        this.row = tblList.getRowCount() -1;
        this.edit();
    }

    @Override
    public void moveNext() {
        if(this.row < tblList.getRowCount() -1){
            ++row;
            this.edit();
        }
    }
    
    @Override
    public void fillComboboxChuyenDe() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboChuyenDe.getModel();
        model.removeAllElements();
        List<ChuyenDe> list = CDdao.selectAll();
        for(ChuyenDe cd : list){
             model.addElement(cd);
        }
    }

    @Override
    public void chonChuyenDe() {
        ChuyenDe chuyende = (ChuyenDe) cboChuyenDe.getSelectedItem();
        txtThoiLuong.setText(chuyende.getThoiLuong()+"");
        txtHocPhi.setText(chuyende.getHocPhi()+"");
        txtGhiChu.setText(chuyende.getMoTa());   
    }

    @Override
    public void insertHocVien() {
        for(int rows:tblNguoiHoc.getSelectedRows()){
            String manh = tblNguoiHoc.getValueAt(rows, 0)+"";
            Integer makh = Integer.valueOf(tblList.getValueAt(this.row, 0)+"");
            HocVien hv = new HocVien();
            hv.setMaNH(manh);
            hv.setMaKH(makh);
            hv.setDiem(0.0);
            HVDAO.insert(hv);
        }
        this.fillToTableHocVien();
        this.fillToTableNguoiHoc();
    }

    @Override
    public void selectAllNH() {
        tblNguoiHoc.setRowSelectionInterval(0, tblNguoiHoc.getRowCount()-1);
    }

    @Override
    public void clearSelectAllNH() {
        tblNguoiHoc.clearSelection();
    }

    @Override
    public void updateDiem() {
        try {
            for(int i=0 ; i< tblHocVien.getRowCount() ; i++){
                int mahv = Integer.parseInt(tblHocVien.getValueAt(i, 0)+"");
                Double diem = Double.valueOf(tblHocVien.getValueAt(i, 5)+"");
                if(XCheck.checkMark(diem)){
                    HocVien hv = new HocVien();
                    hv.setDiem(diem);
                    hv.setMaHV(mahv);
                    HVDAO.update(hv);
                }else{
                    XMsgBox.alert(null,"Sai định dạng điểm.");
                    return;
                }
            }   
            this.fillToTableHocVien();
            XMsgBox.alert(null,"Cập nhật thành công.");
        } catch (Exception e) {
            XMsgBox.alert(null,"Sai định dạng điểm. !!");
        }
        
    }

    @Override
    public void selectAllHV() {
        tblHocVien.setRowSelectionInterval(0, tblHocVien.getRowCount()-1);
    }

    @Override
    public void clearSelectAllHV() {
        tblHocVien.clearSelection();
    }

    @Override
    public void removeHocVien() {
        if(!Auth.isManager()){
            XMsgBox.alert(null,"Bạn không có quyền xóa !!");
        }else {
            if(XMsgBox.confirm(null,"Bạn muốn xóa các học viên được chọn ?")){
                try {
                    for(int rows: tblHocVien.getSelectedRows()){
                    int mahv = Integer.parseInt(tblHocVien.getValueAt(rows, 0)+"");
                        HVDAO.delete(mahv);
                    }
                    XMsgBox.alert(null,"Xóa học viên thành công.");
                } catch (Exception e) {
                    XMsgBox.alert(null,"Xóa học viên thất bại !!");
                }
                this.fillToTableHocVien();
                this.fillToTableNguoiHoc();
            }
        }
    }
}
